clear;
[filename, filepath] = uigetfile({'*.txt;*.csv'});
tmp=readmatrix([filepath,filename]);
scg=tmp(:,7);
scg(scg>32768)=scg(scg>32768)-65536;
ecg=tmp(:,8);
tstp=tmp(:,1);
tstp=tstp/1000000;
tstp=tstp-tstp(1);
scg=scg-mean(scg);
scg=scg/16393;
ecg=ecg-mean(ecg);
tt=timetable(seconds(tstp),scg,ecg);
tt=sortrows(tt);