name: Build for Windows

on:
  push:
    branches: [ CI ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: "Build: ${{ matrix.arch }}"
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch:
          - win64

    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build scg_studio_qt
      run: |
        dir
        tree

 