name: Build for Windows

on:
  push:
    branches: [ CI ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: "Build: ${{ matrix.arch }}"
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch:
          - win64

    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build scg_studio_qt
      run: |
        dir
        echo 1
        cd src_qt\
        echo 2
        dir
        echo 3
        mkdir build
        echo 4
        cd build
        echo 5
        dir
        echo 6
        cmake --build .\build --config ${{env.BUILD_TYPE}} --target all
        echo 7
        mkdir scg_studio_qt
        mv release/scg_studio.exe scg_studio_qt/
        windeployqt scg_studio_qt/scg_studio.exe

    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
          name: scg_studio_qt-${{ matrix.arch }}
          # Use a wildcard to force a subfolder
          path: "build/*-emu/"
          if-no-files-found: error
