name: Build for Windows

on:
  push:
    branches: [ CI ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: "Build: ${{ matrix.arch }}"
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch:
          - win64

    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        py7zrversion: '>=0.20.2'
        version: '6.4.3'
        host: 'windows'
        target: 'desktop'
        arch: '${{ matrix.arch }}_mingw'
        dir: '${{ github.workspace }}/qt6/'
        #modules: 'qt3d qtactiveqt qtcharts qtconnectivity qtdatavis3d qthttpserver qtimageformats qtlanguageserver qtlottie qtmultimedia qtnetworkauth qtpositioning qtquick3dphysics qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qtwebview debug_info qt5compat qtquick3d qtquicktimeline qtshadertools'
        modules: 'qtcharts qtnetworkauth qtserialport'
  
    - name: Build scg_studio_qt
      run: |
        cd src_qt\
        mkdir build
        cd build
        tree ${{github.workspace}}/qt6/Qt/6.4.3/mingw_64/
        cmake ${{github.workspace}}\src_qt -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake -DCMAKE_C_COMPILER=${{github.workspace}}/qt6/Qt/6.4.3/mingw_64/bin/gcc.exe
        cmake --build .\ --target all
        mkdir scg_studio_qt
        mv release/scg_studio.exe scg_studio_qt/
        windeployqt scg_studio_qt/scg_studio.exe

    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
          name: scg_studio_qt-${{ matrix.arch }}
          # Use a wildcard to force a subfolder
          path: "build/*-emu/"
          if-no-files-found: error
